# Generated by Django 5.0.1 on 2024-01-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alerts',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('alertText', models.TextField()),
                ('alertby', models.TextField()),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('atime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='coma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_text', models.TextField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='./img')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('complaintTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CriminalDetails',
            fields=[
                ('crimeid', models.AutoField(primary_key=True, serialize=False)),
                ('aimg', models.FileField(blank=True, null=True, upload_to='./img')),
                ('aname', models.TextField()),
                ('loc', models.TextField()),
                ('age', models.IntegerField()),
                ('gender', models.TextField()),
                ('Noc', models.IntegerField()),
                ('private', models.BooleanField(default=False)),
            ],
        ),
    ]
