# Generated by Django 5.0.1 on 2024-01-29 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coma',
            name='id',
        ),
        migrations.AddField(
            model_name='coma',
            name='acomid',
            field=models.AutoField(default=2, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coma',
            name='aid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='drugapp.criminaldetails'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coma',
            name='clat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coma',
            name='clon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coma',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coma',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coma',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='coma',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
