# Generated by Django 5.0.1 on 2024-01-29 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0002_remove_coma_id_coma_acomid_coma_aid_coma_clat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coma',
            name='aid',
            field=models.IntegerField(),
        ),
    ]
