# Generated by Django 5.0.1 on 2024-01-29 14:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0003_alter_coma_aid'),
    ]

    operations = [
        migrations.AddField(
            model_name='coma',
            name='atime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
