# Generated by Django 5.0.1 on 2024-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugapp', '0004_coma_atime'),
    ]

    operations = [
        migrations.AddField(
            model_name='coma',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
